### ISSUE TITLE
not loading .env

### ISSUE THREAD

**Issue by dmcmillin** [ryanwinchester/netsuite-php#68]
composer require ryanwinchester/netsuite-php then phpdotenv. using example that comes with the readme. 
`<?php
require 'vendor/autoload.php';
use NetSuite\NetSuiteService;
use NetSuite\Classes\SearchStringField;
use NetSuite\Classes\CustomerSearchBasic;
use NetSuite\Classes\SearchRequest;
$service = new NetSuiteService();
$service->setSearchPreferences(false, 20);

$emailSearchField = new SearchStringField();
$emailSearchField->operator = "startsWith";
$emailSearchField->searchValue = "j";

$search = new CustomerSearchBasic();
$search->email = $emailSearchField;

$request = new SearchRequest();
$request->searchRecord = $search;

$searchResponse = $service->search($request);

if (!$searchResponse->searchResult->status->isSuccess) {
    echo "SEARCH ERROR";
} else {
    $result = $searchResponse->searchResult;
    $count = $result->totalRecords;
    $records = $result->recordList;

    echo $count . " records were found.";
}`

along with setting up the .env.

results in this.
`Fatal error: Uncaught RuntimeException: Config key missing: account in /home/api             de/public_html/vendor/ryanwinchester/netsuite-php/src/NetSuiteClient.             php:144
Stack trace:
#0 /home/apide/public_html/vendor/ryanwinchester/netsuite-php/src/Net             SuiteClient.php(57): NetSuite\NetSuiteClient->validateConfig(Array)
#1 /home/apide/public_html/startswithj.php(8): NetSuite\NetSuiteClien             t->__construct()
#2 {main}
  thrown in /home/apide/public_html/vendor/ryanwinchester/netsuite-ph             p/src/NetSuiteClient.php on line 144
`

Please assist.

**Comment by jrebs** [comment]
Hi, at a glance I think the issue is that you're expecting that `netsuite-php` is going to actually load your `.env` file directly. It does not. Loading your netsuite configuration settings from the PHP `$_ENV` superglobal is optionally supported, but it's up to the developer to get those settings loaded into the environment however he or she sees fit.

I think all you probably need to do is add a couple lines to load your config into the environment with dotenv and you're good to go.

**Comment by dmcmillin** [comment]
Decided to go back to using it within the script. weirdly enough its no longer doing it.
